### ISSUE TITLE
Pandas with Python3

### ISSUE THREAD

**Issue by alidursen** [sgerrand/alpine-pkg-py-pandas#13]
first, apparently `23.4` is not availlable yet and we should use `20.3` instead?

second, when i did, that version of `pandas` come with python2 and not python3. is there a way for us to install that way? (ie when tyring to import pandas in py3, module is not found. for py2, it is)

thanks in advance

**Comment by sgerrand** [comment]
Apologies for never responding to your questions. I hope that you've been able to start using the `py3-pandas` package from Alpine Linux directly.
