### ISSUE TITLE
Add .apk to community repo

### ISSUE THREAD

**Issue by jtlz2** [sgerrand/alpine-pkg-py-pandas#6]
So so happy to see this - thank you! Is there any chance you could add it to the Alpine Linux community repo?

https://pkgs.alpinelinux.org/packages

It would be super useful.

Also, have you seen https://github.com/nbgallery/apks ?

Thanks!

**Comment by sgerrand** [comment]
I'm glad you've found it useful! I'll see if I can get it added to the main
aports repository.

**Comment by dimon222** [comment]
Any update on this? It would be amazing if it happens.

It can be submitted in PR
https://github.com/alpinelinux/aports

**Comment by sgerrand** [comment]
Good tip, thanks!

**Comment by sgerrand** [comment]
Opened in alpinelinux/aports#6330. 📿

**Comment by jtlz2** [comment]
@sgerrand Saw this at https://pkgs.alpinelinux.org/package/edge/testing/x86/py-pandas but that link is now dead - was it pulled and why / timescale for replacement?

**Comment by dimon222** [comment]
@jtlz2 https://github.com/alpinelinux/aports/pull/6330#issuecomment-467023544
